100-hours-a-week/20-real-fe

package.json, pnpm-lock.yaml, src/app/(withHeader)/news/[id]/page.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/app/(withHeader)/notices/page.tsx, src/components/Button.tsx, src/components/ImageCarousel.tsx, src/components/MarkdownViewer.tsx, src/components/SingleImage.tsx, src/features/Post/components/PostCommentItem.tsx, src/features/Post/components/PostFileItem.tsx, src/features/Post/components/PostHeader.tsx, src/features/Post/components/PostSummary.tsx, src/features/Post/types/NewsDetail.ts, src/features/Post/types/Notice.ts, src/features/Post/types/NoticeDetail.ts, src/features/Post/types/NoticeFile.tsx, src/features/Post/types/PostComment.ts, src/features/Post/types/PostPlatform.ts
- 게시글(공지, 뉴스) 상세 화면 퍼블리싱
- Closes #10
1. 공지 및 뉴스 상세 화면 퍼블리싱
=> [Feat] 게시글 상세 화면 퍼블리싱

src/api/chatbot.ts, src/app/(withHeader)/chatbot/page.tsx, src/queries/chatbot/usePostChatbotQuestion.ts
=> [Feat] 챗봇 API 연동

src/app/(withHeader)/chatbot/page.tsx, src/app/(withHeader)/layout.tsx, src/app/(withHeader)/login/page.tsx, src/app/(withHeader)/news/[id]/page.tsx, src/app/(withHeader)/news/page.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/app/(withHeader)/notices/page.tsx, src/components/chatbot/HeadlineBanner.tsx, src/components/common/Sidebar.tsx
- 헤더/사이드바 관련 레이아웃 이슈 수정
- Closes #29
1. 일부 확장 플러그인에서 사이드바를 열었을 때 헤더 위치가 잘못 계산되는 이슈 수정
2. 430px보다 작은 화면에서 사이드바 우측이 잘리는 이슈 수정
3. 기타 레이아웃 수정
=> [Fix] 헤더/사이드바 관련 레이아웃 이슈 수정

src/api/fetcher.ts, src/app/(withHeader)/notices/[id]/page.tsx, src/components/post/NoticeListItem.tsx, src/constatns/errors.ts, src/types/user/user.ts
- API 요청 실패 시 에러 문구를 토스트 메시지로 보여지도록 구현
- Closes #37
```ts
export const errors = {
UNAUTHORIZED: '로그아웃 되었어요. 다시 로그인해 주세요.',
FORBIDDEN: '인증된 사용자만 사용할 수 있는 기능이에요.',
DEFAULT: '문제가 생겼어요. 잠시 후 다시 시도해 주세요.',
};
```
=> [Feat] API 에러 시 에러처리

src/api/fetcher.ts, src/app/(withHeader)/news/[id]/page.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/components/post/NewsListItem.tsx, src/components/post/NoticeListItem.tsx, src/components/post/PostHeader.tsx, src/utils/times.ts
=> [Feat] 게시글 태그 확장

src/app/(withHeader)/notices/[id]/page.tsx, src/components/post/PostFileItem.tsx
- 공지에서 첨부파일 클릭 시 파일 다운로드 하도록 구현
- Resolves #50
=> Feat: 공지에서 첨부파일 클릭 시 파일 다운로드 하도록 구현

package.json, pnpm-lock.yaml, src/components/common/MarkdownViewer.tsx
=> [Fix] 마크다운 기능 누락 수정

package.json, pnpm-lock.yaml, src/app/(withHeader)/admin/notices/_components/AdminNoticeForm.tsx, src/app/(withHeader)/admin/notices/edit/[id]/page.tsx, src/components/common/MarkdownViewer.tsx
- 어드민 공지 수정/삭제 기능 구현
- 어드민 공지 작성 시 프리뷰 기능 구현
- Closes #66
=> [Feat] 공지 수정/삭제 및 프리뷰 기능 구현

src/app/(withHeader)/admin/notices/_components/AdminNoticeForm.tsx
- 어드민 공지 편집 이슈 수정
- Resolves #69
1. 공지 수정/삭제 안되는 이슈 수정
2. 공지 수정 시 이미지는 수정 못하도록 수정
3. 이미지/파일을 하나씩 업로드하는 경우 기존 이미지/파일이 사라지는 이슈 수정
=> [Fix] 어드민 공지 수정/삭제 안되는 이슈 수정

package.json, pnpm-lock.yaml, src/components/common/MarkdownViewer.tsx, src/utils/normalizeMarkdown.ts
- 마크다운에서 잘못 렌더링 되는 이슈 수정
- Resolves #77
1. 볼드, 취소선이 정상적으로 렌더링 안되는 이슈 수정
2. 단일 ~ 이스케이프
3. 테이블 내에서 줄 바꿈이 가능하도록 구현
4. 보안 상 위험한 html 태그 차단
=> Fix: 마크다운 렌더링 이슈 수정

src/components/post/PostCommentItem.tsx
- 본인 댓글이 아님에도 삭제 버튼이 보이는 이슈 수정
- Resolves #85
=> Fix: 본인 댓글만 삭제 할 수 있도록 수정

src/app/(withHeader)/chatbot/page.tsx, src/app/(withHeader)/login/page.tsx, src/components/chatbot/BotProfile.tsx, src/components/common/ImageCarousel.tsx, src/components/common/SafeImage.tsx, src/components/common/Sidebar.tsx, src/components/common/SingleImage.tsx, src/components/post/NoticeListItem.tsx, src/components/post/PostCommentItem.tsx
- Image 컴포넌트에서 src를 통해 이미지를 가져오는데 실패할 경우 fallback 처리와 placeholder를 처리하기 위해 SafeImage 래핑 컴포넌트 구현
- Resolves #88
1. SafeImage 컴포넌트 구현
2. 프로젝트의 Image 컴포넌트를 SafeImage로 교채
=> Feat: Image 컴포넌트를 래핑한 SafeImage 컴포넌트 구현

src/app/(withHeader)/chatbot/page.tsx
- 챗봇에서 API 요청이 실패할 경우 크래시 나는 이슈 수정
- Resolves #94
=> Fix: 챗봇에서 API 요청이 실패할 경우 크래시 나는 이슈 수정

src/app/(withHeader)/layout.tsx, src/app/layout.tsx, src/utils/times.ts
- 430px 모바일 화면에서 화면이 잘리는 이슈 수정
- Resolves #96
=> Feat: 작은 모바일 화면에도 너비 대응하도록 구현

src/api/auth.ts, src/app/(withHeader)/news/[id]/page.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/app/globals.css, src/app/not-found.tsx, src/components/common/Header.tsx, src/components/common/NotFound.tsx, src/components/common/Sidebar.tsx, src/queries/base/useInfiniteCursorQuery.ts, src/utils/times.ts
- 로그아웃 기능 구현
- Resolves #80
1. 로그아웃 기능 구현
2. 404 페이지 구현
3. 기타 버그 수정
=> Feat: 로그아웃 기능 구현

package.json, pnpm-lock.yaml, src/app/providers.tsx, src/components/common/Button.tsx, src/components/common/ImageCarousel.tsx, src/components/common/Modal.tsx, src/components/common/Sidebar.tsx, src/components/post/PostCommentList.tsx, src/components/post/PostLikeButton.tsx, src/stores/modalStore.ts, src/stories/Button.stories.tsx, src/stories/ImageCarousel.stories.tsx, src/stories/Input.stories.tsx, src/stories/MarkdownViewer.stories.tsx, src/stories/Modal.stories.tsx, src/stories/SafeImage.stories.tsx, src/stories/Sidebar.stories.tsx, src/stories/ToastContainer.stories.tsx
- 공통 컴포넌트에 대한 Story를 정의하여 시각화
- Resolves #93
1. 공통 컴포넌트 Storybook 시각화
- Storybook Publish는 main 머지하면 배포되도록 github actions 설정됨
=> Feat: 공통 컴포넌트 Storybook 시각화

src/api/fetcher.ts, src/app/(withHeader)/news/[id]/page.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/components/common/Button.tsx, src/components/common/RedirectWithModal.tsx
- 기존 로그인 안한 상태에서 게시글 상세 접근 시 404로 안내했습니다.
- 로그인 유도 모달을 띄워 사용자의 상태를 바로 알 수 있게 수정했습니다.
- Resolves #112
=> Feat: 로그인 안한 상태로 게시글 상세 접근 시 로그인 유도 모달을 띄우도록 구현

src/api/chatbot.ts, src/api/fetcher.ts, src/api/news.ts, src/api/post.ts, src/api/user.ts, src/app/(withHeader)/news/[id]/page.tsx, src/app/global-error.tsx, src/components/common/pages/ErrorPage/ErrorPage.tsx, src/components/common/pages/ErrorPage/index.ts, src/components/common/pages/NotFoundPage/NotFoundPage.tsx, src/components/post/organisms/PostDetailSection/PostDetailSection.tsx, src/components/post/pages/NewsDetailPage/NewsDetailPage.tsx, src/components/post/pages/NoticeDetailPage/NoticeDetailPage.tsx, src/constatns/errors.ts, src/lib/errors/appError.ts, src/lib/errors/errorLevels.ts, src/lib/errors/errorTags.ts, src/lib/errors/errors.ts, src/queries/base/useApiQuery.ts, src/queries/base/useInfiniteCursorQuery.ts, src/queries/news/useNewsDetailQuery.ts, src/queries/news/useNewsListQuery.ts, src/queries/post/useNoticeDetailQuery.ts
- 에러 처리하는 로직 변경
- Resolves #134
1. 에러 처리 로직 변경
2. 전역 에러 페이지 구현
3. 게시물 상세 리팩토링
=> Refactor: 에러 처리 구조 변경

src/api/fetcher.ts, src/components/chatbot/organisms/ChatItem/ChatItem.tsx, src/components/chatbot/pages/ChatbotPage/ChatbotPage.tsx, src/hooks/useChatController.ts, src/lib/errors/appError.ts, src/lib/errors/errorTags.ts, src/lib/errors/errors.ts, src/types/chatbot/chatMessage.ts
- 챗봇 응답 SSE로 받도록 구현
- Resolves #144
1. 챗봇 응답 SSE로 받도록 구현
2. 챗봇 응답 에러 시 UI 안내
3. 챗봇 운영 시간 외 요청 시 UI 안내
https://github.com/user-attachments/assets/d418e2be-d6af-4c9d-9635-74d06676dc13
=> Feat: 챗봇 응답 SSE로 받도록 구현

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
- Resolves #[이슈 번호]
1. dev 브랜치에서 storybook test 삭제 및 임시 빌드 테스트 주석
2. dev, prod에서 aws region 변수가 잘못 들어가던 현상 수정
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> 🐛 fix : fix cicd error

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
- Resolves #[이슈 번호]
1.  fix ssm url
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> 🐛 fix : fix ssm url

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
=> 🐛 fix : fix ssm logic

.github/workflows/deploy-dev.yml
=> 🐛 fix : remove annotation

.github/workflows/deploy-dev.yml
=> 🐛 fix : yml fix

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml
=> 🐛 fix : fix timeout

Dockerfile
Dockerfile builder stage -> runner stage next 환경파일 이식
1. Dockerfile 수정
=> 🐛 fix: Dockerfile Staging File Injection

src/widgets/wiki/sections/WikiEditor/WikiEditor.tsx
- 소켓에 연결된 상태에서만 서버로 수정 내용을 전송하도록 수정
- Resolves #194
=> Fix: 소켓에 연결된 상태에서만 서버로 수정 내용을 전송하도록 수정

src/widgets/wiki/sections/WikiEditor/WikiEditor.tsx
- 기존엔 위키에 들어가면 바로 스냅샷 전송을 시작해서 updatedAt이 항상 갱신됐음
- 해당 이슈 방지로 위키 편집이 발생하면 그때부터 스냅샷 전송을 활성화하도록 수정함
- Resolves #203
=> Fix: 위키 편집이 발생하면 그때부터 BE로 스냅샷 전송하도록 수정

scripts/deploy.sh
코드디플로이 실행 스크립트에 ysocket pull과 run 추가
=> 🚀 deploy: ysocket container

src/app/(withHeader)/news/page.tsx, src/shared/ui/component/EmptyItem/EmptyItem.tsx, src/shared/ui/component/ErrorHandler/ErrorHandler.tsx, src/widgets/post/components/NewsListHeader/NewsListHeader.tsx, src/widgets/post/components/NewsListHeader/index.ts, src/widgets/post/sections/HotNewsList/HotNewsList.stories.tsx, src/widgets/post/sections/HotNewsList/HotNewsList.test.tsx, src/widgets/post/sections/HotNewsList/HotNewsList.tsx, src/widgets/post/sections/HotNewsList/index.ts, src/widgets/post/sections/NewsList/NewsList.stories.tsx, src/widgets/post/sections/NewsList/NewsList.test.tsx, src/widgets/post/sections/NewsList/NewsList.tsx, src/widgets/post/sections/NewsList/index.ts, test/mocks/post/data/newsList/empty.json, test/mocks/post/data/newsList/hotNewsSuccess.json, test/mocks/post/data/newsList/newsSuccess.json, test/mocks/post/handlers/newsList.handlers.ts
- 뉴스 도메인 관련 리팩토링 및 테스트 작성
- Resolves #209
1. 뉴스 리스트 테스트 코드 및 스토리 작성
2. 뉴스 리스트에서 누락된 에러 핸들링 구현
=> Test: 뉴스 도메인 관련 리팩토링 및 테스트 작성

next.config.ts
- Next에서 이미지 최적화 하는 경우 Avif 포맷도 지원하도록 설정
- Resolves #221
1. Avif 지원하는 경우 9% 이미지 크기 감소, 7.5%속도 개산
=> Setting: 이미지에서 avif 포맷도 지원하도록 설정

src/app/(withHeader)/admin/layout.tsx, src/app/(withHeader)/admin/notices/_components/AdminNoticeForm.tsx, src/app/(withHeader)/notices/[id]/page.tsx, src/features/post/api/notices.ts, src/features/post/dto/postNoticeRequest.ts, src/features/post/dto/putNoticeRequest.ts, src/features/post/model/hooks/useAdminNoticeForm.ts, src/features/post/model/notices/useCreateNoticeMutation.ts, src/features/post/model/notices/useDeleteNoticeMutation.ts, src/features/post/model/notices/useEditNoticeMutation.ts, src/shared/lib/utils/fetcher.ts, src/shared/ui/component/NotFoundPage/NotFoundPage.tsx, src/shared/ui/section/Sidebar/Sidebar.tsx, src/widgets/post/components/NoticeInfoSelect/NoticeInfoSelect.tsx, src/widgets/post/components/PostHeader/PostHeader.tsx
- 어드민 페이지 고도화. (UI 개선, 접근 제어 등)
- Resolves #220
1. 어드민 공지 작성 페이지 UI 개선
2. 사이드바에서 어드민 메뉴가 보여지도록 구현
3. 어드민 페이지 접근 시 유저 role이 staff가 아니라면 렌더링하지 않도록 접근 제어
4. 공지 편집/제거에 접근 할 수 있도록 공지 상세에 버튼 구현
=> Feat: 어드민 페이지 고도화

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, scripts/deploy-dev.sh, scripts/deploy-prod.sh, scripts/stop.sh
codedeploy application 네임을 브랜치 별로 분리하였음
=> 🚑 !HOTFIX : divide codedeploy application name

src/shared/lib/utils/fetcher.ts, src/shared/model/userPersistStore.ts
- refresh 성공 후 유저 정보를 다시 가져오도록 구현
- Resolves #243
=> Fix: token refresh 후 유저 정보 가져오도록 구현

.gitignore, package.json, playwright.config.ts, pnpm-lock.yaml, src/app/(withHeader)/wiki/[title]/page.tsx, src/widgets/chatbot/sections/ChatbotSection/ChatbotSection.test.tsx, test/e2e/wiki.spec.ts, test/utils/createLoginContext.ts
- 기존 통합테스트에선 제한되던 동시 편집 기능을 Playwright의 multi context를 사용하여 테스트를 작성했습니다.
- Resolves #225
1. 동시 편집 관련 테스트 작성
- CI 환경(dev 서버 타겟): pnpm playwright:prod 
- 로컬 환경(로컬 서버 타겟): pnpm playwright:dev
=> Test: 위키 동시 편집 E2E 테스트 작성

src/shared/ui/section/NotificationDropdown/NotificationDropdown.tsx
- 알림 기능(안 읽은 공지)에 SSE를 연동하여 실시간 알림이 오도록 구현
- Resolves #246
=> Feat: 알림 기능 SSE 연동

src/otel.ts
OTEL Collector endpoint 수정
1. [OTEL 콜렉터 엔드포인트 분할 및 수정]
=> 🐛 fix: OTEL Endpoint
